name: Build and Test

on:
  push:
    branches: [ main, develop, copilot/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  secrets-safety-scan:
    name: Secrets Safety Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for proper diff

      - name: Run secrets check script
        run: |
          chmod +x tools/check-for-secrets.sh
          ./tools/check-for-secrets.sh

  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    needs: secrets-safety-scan
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create placeholder google-services.json for CI build
        run: |
          cat > app/google-services.json << 'EOF'
          {
            "project_info": {
              "project_number": "000000000000",
              "project_id": "ci-build-placeholder",
              "storage_bucket": "ci-build-placeholder.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:000000000000:android:0000000000000000",
                  "android_client_info": {
                    "package_name": "com.vxsudev.androidsdk"
                  }
                },
                "oauth_client": [],
                "api_key": [
                  {
                    "current_key": "CI_BUILD_PLACEHOLDER_KEY"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOF

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 7

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    needs: secrets-safety-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create placeholder google-services.json for CI
        run: |
          cat > app/google-services.json << 'EOF'
          {
            "project_info": {
              "project_number": "000000000000",
              "project_id": "ci-build-placeholder",
              "storage_bucket": "ci-build-placeholder.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:000000000000:android:0000000000000000",
                  "android_client_info": {
                    "package_name": "com.vxsudev.androidsdk"
                  }
                },
                "oauth_client": [],
                "api_key": [
                  {
                    "current_key": "CI_BUILD_PLACEHOLDER_KEY"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOF

      - name: Run Lint
        run: ./gradlew lint

      - name: Upload Lint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results*.html
          retention-days: 7

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: secrets-safety-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create placeholder google-services.json for CI
        run: |
          cat > app/google-services.json << 'EOF'
          {
            "project_info": {
              "project_number": "000000000000",
              "project_id": "ci-build-placeholder",
              "storage_bucket": "ci-build-placeholder.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:000000000000:android:0000000000000000",
                  "android_client_info": {
                    "package_name": "com.vxsudev.androidsdk"
                  }
                },
                "oauth_client": [],
                "api_key": [
                  {
                    "current_key": "CI_BUILD_PLACEHOLDER_KEY"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOF

      - name: Run Unit Tests
        run: ./gradlew test --stacktrace

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: app/build/reports/tests/
          retention-days: 7

      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: app/build/test-results/**/*.xml
