name: Build and Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
  JAVA_TOOL_OPTIONS: -Xmx2g

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest

      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" \
                              "platforms;android-34" \
                              "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Gradle — assembleDebug
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Gradle — lint
        run: ./gradlew lint --no-daemon --stacktrace

      - name: Gradle — unit tests
        run: ./gradlew test --no-daemon --stacktrace

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn

      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: |
            app/build/reports/lint-results*.html
            app/build/reports/lint-results*.xml
            app/build/reports/lint-results*.sarif
          if-no-files-found: warn

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: |
            app/build/test-results/testDebugUnitTest/*.xml
            app/build/reports/tests/testDebugUnitTest/*
          if-no-files-found: warn

