name: Build and Test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_TOOL_OPTIONS: -Xmx2g

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create placeholder google-services.json for CI build
        run: |
          mkdir -p app
          echo '{}' > app/google-services.json

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Lint Check
        run: ./gradlew lint

      - name: Unit Tests
        run: ./gradlew test

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            app/build/reports/
            app/build/outputs/

